#!/usr/bin/env bash
# Runs on EVERY container start (postStartCommand). Re-sources .env, then
# reports auth state, so a rotated Keychain value takes effect on restart
# rather than needing a full rebuild.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# runArgs --env-file applies only at create; this hook makes restarts enough.
if [ -f "$ENV_FILE" ]; then
  set -a; . "$ENV_FILE"; set +a
  TMP=$(mktemp)
  cat > "$TMP" <<EOF
#!/bin/sh
# Auto-generated by .devcontainer/check-auth.sh — do not edit.
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi
EOF
  sudo install -m 0644 -o root -g root "$TMP" /etc/profile.d/devcontainer-env.sh
  rm -f "$TMP"
fi

echo ""
echo "═══════════════ environment ═══════════════"

if gh auth status &>/dev/null; then
  echo "  ✓ GitHub CLI — authenticated (Eaiger-Ent via GITHUB_TOKEN)"
elif [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "  ✗ GitHub CLI — GITHUB_TOKEN set but rejected (expired? wrong scopes?)"
else
  echo "  ✗ GitHub CLI — not authenticated. Run: gh auth login"
fi

if [ -n "${EE_SKILLS_GITHUB_TOKEN:-}" ]; then
  if env -u GITHUB_TOKEN GH_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" gh auth status &>/dev/null; then
    echo "  ✓ gh-ee-skills — authenticated (EqualExperts via EE_SKILLS_GITHUB_TOKEN)"
  else
    echo "  ✗ gh-ee-skills — EE_SKILLS_GITHUB_TOKEN set but rejected (expired? wrong scopes?)"
  fi
else
  echo "  ✗ gh-ee-skills — no EE_SKILLS_GITHUB_TOKEN. See docs/06-devcontainer-setup.md"
fi

if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  echo "  ✓ Claude Code — OAuth token present (subscription billing)"
else
  echo "  ✗ Claude Code — no OAuth token. See docs/06-devcontainer-setup.md"
fi

for tool in claude python3 node markdownlint-cli2; do
  if command -v "$tool" &>/dev/null; then
    echo "  ✓ ${tool} — $("$tool" --version 2>/dev/null | head -1)"
  else
    echo "  ✗ ${tool} — missing (re-run: bash .devcontainer/setup.sh)"
  fi
done

if git config user.email &>/dev/null; then
  echo "  ✓ git — $(git config user.name) <$(git config user.email)>"
else
  echo "  ✗ git — identity not configured"
fi

echo "═══════════════════════════════════════════"
echo ""
