#!/usr/bin/env bash
# Runs on EVERY container start (postStartCommand). Re-sources .env, then
# reports auth state, so a rotated Keychain value takes effect on restart
# rather than needing a full rebuild.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$SCRIPT_DIR/.env"

# runArgs --env-file applies only at create; this hook makes restarts enough.
if [ -f "$ENV_FILE" ]; then
  set -a; . "$ENV_FILE"; set +a
  TMP=$(mktemp)
  cat > "$TMP" <<EOF
#!/bin/sh
# Auto-generated by .devcontainer/check-auth.sh — do not edit.
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi
EOF
  sudo install -m 0644 -o root -g root "$TMP" /etc/profile.d/devcontainer-env.sh
  rm -f "$TMP"
fi

echo ""
echo "═══════════════ environment ═══════════════"

if gh auth status &>/dev/null; then
  echo "  ✓ GitHub CLI — authenticated (Eaiger-Ent via GITHUB_TOKEN)"
elif [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "  ✗ GitHub CLI — GITHUB_TOKEN set but rejected (expired? wrong scopes?)"
else
  echo "  ✗ GitHub CLI — not authenticated. Run: gh auth login"
fi

if [ -n "${EE_SKILLS_GITHUB_TOKEN:-}" ]; then
  if env -u GITHUB_TOKEN GH_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" gh auth status &>/dev/null; then
    echo "  ✓ gh-ee-skills — authenticated (EqualExperts via EE_SKILLS_GITHUB_TOKEN)"
  else
    echo "  ✗ gh-ee-skills — EE_SKILLS_GITHUB_TOKEN set but rejected (expired? wrong scopes?)"
  fi
else
  echo "  ✗ gh-ee-skills — no EE_SKILLS_GITHUB_TOKEN. See docs/06-devcontainer-setup.md"
fi

if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  echo "  ✓ Claude Code — OAuth token present (subscription billing)"
else
  echo "  ✗ Claude Code — no OAuth token. See docs/06-devcontainer-setup.md"
fi

# Probe each tool the way its loci actually invoke it. DOC-001's markdownlint is
# pinned by package-lock.json and run as `npx markdownlint-cli2` at every locus,
# so it lives in node_modules/.bin and never on PATH — probing for a bare binary
# reported it missing on a container where every locus runs it fine. npx resolves
# it from the repository, not from wherever this hook happens to be invoked.
check_tool() {
  local label="$1" out first
  shift
  if out=$(cd "$REPO_DIR" && "$@" --version 2>/dev/null); then
    first=$(printf '%s\n' "$out" | head -1)
  else
    first=""
  fi
  if [ -n "$first" ]; then
    echo "  ✓ ${label} — ${first}"
  else
    echo "  ✗ ${label} — missing (re-run: bash .devcontainer/setup.sh)"
  fi
}

check_tool claude claude
# Not a bare `python3`: there is no system interpreter any more (ADR 0030), and
# probing for one reported "missing" on a container where every locus works.
# `uv run python` is the question the loci actually ask.
check_tool python uv run python
check_tool node node
# `node_modules/.bin/...`, not `npx --no-install`: ADR 0020 measured that
# spelling falling through to `PATH`, so a probe using it can report a global
# copy as though it were the pinned one — the opposite of what this script is
# for. The register's `tools.markdownlint-cli2.invocation` is the authority.
check_tool markdownlint-cli2 node_modules/.bin/markdownlint-cli2
# The one tool `setup.sh` installs itself, and the one every verification here
# runs through.
check_tool uv uv

# **A wired locus with no installed hook.** `.pre-commit-config.yaml` states
# intent and `.git/hooks/<type>` is whether anything runs, and every control
# that declares a local locus reads the first. Reported, never repaired: a
# start-up hook that silently fixed state would hide which locus stopped working
# and when. It cannot be a control either — `.git/hooks/` is untracked, and CI
# has no hooks installed and should not.
#
# Two hook types since register contract 31 (ADR 0039), asked separately because
# they fail separately: `pre-commit install` without `--hook-type pre-push`
# leaves the second locus wired in the config and running nothing, which is
# exactly the half-state this block exists to name.
if [ -f "$REPO_DIR/.pre-commit-config.yaml" ]; then
  for hook_type in pre-commit pre-push; do
    if [ -x "$REPO_DIR/.git/hooks/$hook_type" ]; then
      echo "  ✓ $hook_type hook — installed"
    else
      echo "  ✗ $hook_type hook — .pre-commit-config.yaml is present and"
      echo "      .git/hooks/$hook_type is not. Nothing runs at the $hook_type"
      echo "      locus. Fix: bash .devcontainer/setup.sh"
    fi
  done
fi

# Identity may come from git config or from GIT_AUTHOR_* in the environment
# (fetch-secrets.sh supplies the latter). `git var` is the question actually
# being asked — can git name an author? — and answers it whichever way it is set.
if ident=$(git var GIT_AUTHOR_IDENT 2>/dev/null); then
  echo "  ✓ git — ${ident% * *}"
else
  echo "  ✗ git — identity not configured"
fi

echo "═══════════════════════════════════════════"
echo ""
