#!/usr/bin/env bash
# Runs on EVERY container start (postStartCommand). Re-sources .env, then
# reports auth state, so a rotated Keychain value takes effect on restart
# rather than needing a full rebuild.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$SCRIPT_DIR/.env"

# runArgs --env-file applies only at create; this hook makes restarts enough.
if [ -f "$ENV_FILE" ]; then
  set -a; . "$ENV_FILE"; set +a
  TMP=$(mktemp)
  cat > "$TMP" <<EOF
#!/bin/sh
# Auto-generated by .devcontainer/check-auth.sh — do not edit.
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi
EOF
  sudo install -m 0644 -o root -g root "$TMP" /etc/profile.d/devcontainer-env.sh
  rm -f "$TMP"
fi

echo ""
echo "═══════════════ environment ═══════════════"

if gh auth status &>/dev/null; then
  echo "  ✓ GitHub CLI — authenticated (Eaiger-Ent via GITHUB_TOKEN)"
elif [ -n "${GITHUB_TOKEN:-}" ]; then
  echo "  ✗ GitHub CLI — GITHUB_TOKEN set but rejected (expired? wrong scopes?)"
else
  echo "  ✗ GitHub CLI — not authenticated. Run: gh auth login"
fi

if [ -n "${EE_SKILLS_GITHUB_TOKEN:-}" ]; then
  if env -u GITHUB_TOKEN GH_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" gh auth status &>/dev/null; then
    echo "  ✓ gh-ee-skills — authenticated (EqualExperts via EE_SKILLS_GITHUB_TOKEN)"
  else
    echo "  ✗ gh-ee-skills — EE_SKILLS_GITHUB_TOKEN set but rejected (expired? wrong scopes?)"
  fi
else
  echo "  ✗ gh-ee-skills — no EE_SKILLS_GITHUB_TOKEN. See docs/06-devcontainer-setup.md"
fi

if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  echo "  ✓ Claude Code — OAuth token present (subscription billing)"
else
  echo "  ✗ Claude Code — no OAuth token. See docs/06-devcontainer-setup.md"
fi

# Probe each tool the way its loci actually invoke it. DOC-001's markdownlint is
# pinned by package-lock.json and run as `npx markdownlint-cli2` at every locus,
# so it lives in node_modules/.bin and never on PATH — probing for a bare binary
# reported it missing on a container where every locus runs it fine. npx resolves
# it from the repository, not from wherever this hook happens to be invoked.
check_tool() {
  local label="$1" out first
  shift
  if out=$(cd "$REPO_DIR" && "$@" --version 2>/dev/null); then
    first=$(printf '%s\n' "$out" | head -1)
  else
    first=""
  fi
  if [ -n "$first" ]; then
    echo "  ✓ ${label} — ${first}"
  else
    echo "  ✗ ${label} — missing (re-run: bash .devcontainer/setup.sh)"
  fi
}

check_tool claude claude
# Not a bare `python3`: there is no system interpreter any more (ADR 0030), and
# probing for one reported "missing" on a container where every locus works.
# `uv run python` is the question the loci actually ask.
check_tool python uv run python
check_tool node node
check_tool markdownlint-cli2 npx --no-install markdownlint-cli2

# Identity may come from git config or from GIT_AUTHOR_* in the environment
# (fetch-secrets.sh supplies the latter). `git var` is the question actually
# being asked — can git name an author? — and answers it whichever way it is set.
if ident=$(git var GIT_AUTHOR_IDENT 2>/dev/null); then
  echo "  ✓ git — ${ident% * *}"
else
  echo "  ✗ git — identity not configured"
fi

echo "═══════════════════════════════════════════"
echo ""
