#!/usr/bin/env bash
# Runs on container create (postCreateCommand).
#
# Deliberately short. Per docs/03-devcontainer.md, anything long enough to need
# sectioning is doing work that belongs in the image or a pinned feature.
# Everything installable here is a feature; what remains is wiring.
set -euo pipefail

# The named volume mounts root-owned on first create.
sudo chown -R vscode:vscode /home/vscode/.claude

# markdownlint-cli2 at the version the register records for DOC-001, so the
# editor and CI cannot disagree about what the control means (theme T-2).
# Change this and the CI pin together, never one alone.
npm install -g markdownlint-cli2@0.23.2

# The host ~/.gitconfig may name a Homebrew gh path that does not exist here.
GH_BIN="$(command -v gh)"
for host in github.com gist.github.com; do
  git config --global --unset-all "credential.https://${host}.helper" || true
  git config --global --add "credential.https://${host}.helper" \
    "!${GH_BIN} auth git-credential"
done

# GITHUB_TOKEN (above) is scoped to Eaiger-Ent and shadows gh's ambient auth
# for every host, so a second PAT for the EqualExperts org (ee-skills,
# ee-skills-incubator, generate-ee-slides) can't just be a second env var —
# gh only honours one GH_TOKEN/GITHUB_TOKEN at a time. This wrapper scopes it
# to a single invocation instead: `gh-ee-skills issue create ...`.
sudo install -m 0755 /dev/stdin /usr/local/bin/gh-ee-skills <<'EOF'
#!/usr/bin/env bash
# Auto-generated by .devcontainer/setup.sh — do not edit.
# Runs gh authenticated as the EqualExperts-org PAT, scoped to this call only.
set -euo pipefail
if [ -z "${EE_SKILLS_GITHUB_TOKEN:-}" ]; then
  echo "gh-ee-skills: EE_SKILLS_GITHUB_TOKEN not set (see docs/06-devcontainer-setup.md)" >&2
  exit 1
fi
exec env -u GITHUB_TOKEN GH_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" gh "$@"
EOF

# The ee-skills plugins this repo's workflow depends on (docs/02-skill-family.md).
# Plugin state lives in the ~/.claude volume, so this only does work on a fresh
# volume. The marketplace repo is private to the EqualExperts org, so both the
# add and the installs run under the second PAT — the ambient GITHUB_TOKEN is
# Eaiger-Ent-scoped and cannot clone it.
if [ -n "${EE_SKILLS_GITHUB_TOKEN:-}" ]; then
  if ! claude plugin marketplace list 2>/dev/null | grep -q "EqualExperts/ee-skills"; then
    GITHUB_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" GH_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" \
      claude plugin marketplace add EqualExperts/ee-skills
  fi
  installed="$(claude plugin list 2>/dev/null || true)"
  for plugin in adr-toolkit lint-md devcontainer-check skill-preflight ee-skills-manage clarify-all; do
    echo "${installed}" | grep -q "${plugin}@ee-skills" && continue
    GITHUB_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" GH_TOKEN="${EE_SKILLS_GITHUB_TOKEN}" \
      claude plugin install "${plugin}@ee-skills"
  done
else
  echo "⚠ EE_SKILLS_GITHUB_TOKEN not set — skipping ee-skills plugin install" >&2
fi

echo "✓ setup complete"
